#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';

use Jazzyweb\Bookmaker\Command\PublishCommand;
use Jazzyweb\Bookmaker\Command\ListCommand;
use Jazzyweb\Bookmaker\Application\Application;


$application = new Application(__DIR__.'/../config/config.yml');

$application->run();